### PR TITLE
Refactored UI to separate HTML into `.html` files

### PR DESCRIPTION
**Pull request by Jython1415**
- [x] Ready for review
- [ ] Review completed

### CODE REVIEW

**Comment by Jython1415** [comment]
I'm currently refactoring the component HTML so that it can be in its own file. Still have to do the following:

- [ ] taskpage
- [ ] user-form
- [ ] users-list

**Comment by Jython1415** [comment]
Marked ready for review so that the UI refactoring can be merged into main *before* I work on the log-in UI changes

**Comment by Jython1415** [comment]
Requesting review from @juldyzmurat and @HaruJGG because you worked on UI code before. Everything looks good on my end, but please check to make sure it looks okay on your end. Once that is done I will merge and continue work on the log-in UI

**Review by HaruJGG — APPROVED** [review]
Looks good, nothing that should break given the moving of HTML to HTML files.

**Pull request merged**
